services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      TZ: "Europe/Amsterdam"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"

  spark-master:
    image: apache/spark:4.1.1-scala
    container_name: spark-master
    command: /opt/spark/sbin/start-master.sh
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_NO_DAEMONIZE: "true"
      HOME: /opt/spark/work-dir
      SPARK_SUBMIT_OPTS: "-Duser.home=/opt/spark/work-dir"
      SPARK_OPTS: "-Dscala.shell.histfile=/tmp/.spark_history"
    ports:
      - "7077:7077"
      - "9090:8080"
      - "4040:4040"
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./spark-data:/opt/spark-data

  spark-worker:
    image: apache/spark:4.1.1-scala
    command: /opt/spark/sbin/start-worker.sh spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1G
      SPARK_NO_DAEMONIZE: "true"
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./spark-data:/opt/spark-data
